PMM-7410 use grafana api for operations with folders
percona/pmm-server pull request #279
Opened 2021-07-01 12:21 UTC by adivinho

2021-07-01 14:45 UTC, askomorokhov requested changes
Please fix minor issues.

2021-07-01 14:45 UTC, askomorokhov commented on import-dashboards.py
> +                    print '     * Compare dashboard is detected for the service %s' % match_compare.group(0);
```suggestion
                    print '     * Compare dashboard is detected for the service %s' % (match_compare.group(0),);
```

please use tuples for string formating

2021-07-01 14:45 UTC, askomorokhov commented on import-dashboards.py
> +                    print '     * HA dashboard is detected for the service %s' % match_ha.group(0);
```suggestion
                    print '     * HA dashboard is detected for the service %s' % (match_ha.group(0),);
```

2021-07-01 14:45 UTC, askomorokhov commented on import-dashboards.py
> +            r = requests.post('%s/api/dashboards/db' % (HOST), headers=grafana_headers(api_key), data=json.dumps(dash_data), verify=False)
```suggestion
            r = requests.post('%s/api/dashboards/db' % (HOST,), headers=grafana_headers(api_key), data=json.dumps(dash_data), verify=False)
```

missed comman in tuple `(HOST,)`

2021-07-01 15:01 UTC, askomorokhov approved these changes
Cool!  😎 Looks good to me! 👍

2021-07-01 19:11 UTC, BupycHuk approved these changes

2021-07-05 19:22 UTC, atymchuk approved these changes

2021-07-07 13:44 UTC, nikita-b approved these changes

2021-07-19 10:15 UTC, merged