Update dbaas-tools.spec
percona/pmm-server pull request #359
Opened 2022-05-04 09:11 UTC by BupycHuk

2022-05-04 09:37 UTC, nikita-b commented
@BupycHuk It's a bad package and won't work without additional changes:
1. We need to change this `sed` because goreleaser config was changed.
https://github.com/percona/pmm-server/blob/03f88561c8d4489e97c48865f0b757723a5eca2d/rhel/SPECS/dbaas-tools.spec#L57
2. https://github.com/percona/pmm-server/blob/03f88561c8d4489e97c48865f0b757723a5eca2d/rhel/SPECS/dbaas-tools.spec#L58
The original package doesn't have `make build` anymore:
https://github.com/kubernetes-sigs/aws-iam-authenticator/blob/master/Makefile#L70
3. We need to add a changelog.

2022-05-04 09:48 UTC, BupycHuk commented
Thanks @nikita-b , updated

2022-05-04 10:14 UTC, nikita-b approved these changes

2022-05-04 18:03 UTC, denisok commented
@BupycHuk should you also update CI in DBaaS: https://github.com/percona-platform/dbaas-controller/blob/main/.github/workflows/ci.yml#L267 ?

2022-05-09 20:08 UTC, denisok commented
https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-submodules/detail/PR-2511/1/pipeline

`binary=dist/aws-iam-authenticator_linux_amd64_v1/aws-iam-authenticator`

probably path was changed, and copying from different path `install -D -p -m 0755 dist/authenticator_linux_amd64/aws-iam-authenticator`

2022-05-09 20:10 UTC, denisok requested changes

2022-05-09 20:10 UTC, denisok commented on rhel/SPECS/dbaas-tools.spec
>  install -D -p -m 0755 dist/authenticator_linux_amd64/aws-iam-authenticator %{buildroot}/opt/dbaas-tools/bin/aws-iam-authenticator
```suggestion
install -D -p -m 0755 dist/aws-iam-authenticator_linux_amd64_v1/aws-iam-authenticator %{buildroot}/opt/dbaas-tools/bin/aws-iam-authenticator
```

2022-05-09 20:12 UTC, denisok commented
> https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-submodules/detail/PR-2511/1/pipeline
> 
> `binary=dist/aws-iam-authenticator_linux_amd64_v1/aws-iam-authenticator`
> 
> probably path was changed, and copying from different path `install -D -p -m 0755 dist/authenticator_linux_amd64/aws-iam-authenticator`

https://github.com/Percona-Lab/pmm-submodules/pull/2511

2022-05-10 10:03 UTC, denisok approved these changes

2022-05-17 12:24 UTC, merged